name: teste_pratico_mobile
description: "Um desafio Flutter"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  intl: ^0.20.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.4

flutter:


  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  color: "#0500FF"
  image: assets/logo/BeTalent.png
  fullscreen: true
